### ISSUE TITLE
After running I’m stuck in a black screen

### ISSUE THREAD

**Issue by wbehrens-on-gh** [endumiuz/vfio-bind#1]
after running the script and rebooting I’m in a black screen help! I don’t know what other info you need so ask if I’m not specific enough, I have a 2070 super and I’m running the newest version of solus

**Comment by wbehrens-on-gh** [comment]
OK, after looking through it I'm stupid, I just realized I'd need a second GPU for this to work, to change back the drivers do I just run the uninstall script?

**Comment by endumiuz** [comment]
Yes, the uninstall script should restore everything
